---
# Configure NTP
#
- name: Install NTP package
  apt: name=ntp state=latest

- name: Drop NTP configuration from template
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644 backup=yes
  notify: Restart NTP
